### ISSUE TITLE
c and C might be mixed up

### ISSUE THREAD

**Issue by jlchereau** [andrewrk/node-diacritics#16]
![image](https://cloud.githubusercontent.com/assets/2556751/10964264/f5f6eab6-839d-11e5-814a-3a12cdd80d74.png)

![image](https://cloud.githubusercontent.com/assets/2556751/10964288/20e59dd0-839e-11e5-9c97-eabadb7afe25.png)

**Comment by edravis** [comment]
@andrewrk Maybe the background of this issue is the lack of testing?

**Comment by jlchereau** [comment]
Whoa that's quick! but I am not sure what you mean.
Do you recommend not using this piece of code?

**Comment by andrewrk** [comment]
Fixed, and published in 1.2.3.
