### ISSUE TITLE
Work in console but not in my code

### ISSUE THREAD

**Issue by douineauromain** [andrewrk/node-diacritics#17]
Hi, thanks for this tool but i've a very strange bug, i use node.js webkit.

It don't work in my function :
![image](https://cloud.githubusercontent.com/assets/8361263/11098426/33702978-88a5-11e5-9820-283e9e656d7d.png)

But it work when i call the function in the console :unamused: :
![image](https://cloud.githubusercontent.com/assets/8361263/11098465/6eb1ae62-88a5-11e5-948a-001f65023d57.png)

WTF ? Do you have any idea ? Thanks

**Comment by thejoshwolfe** [comment]
Does it work when you actually run the code? Like does the code do the right thing? It looks like the problem is just in the debugger's display of the local variable.

**Comment by douineauromain** [comment]
Thanks for your fast response. But yes it don't work when i run my code :(

**Comment by thejoshwolfe** [comment]
I don't know what the problem could be. It's probably something subtle, like the name `removeDiacritics` resolves do a shadowed symbol in some context but not another. I'm not sure how that could be the case, but it sounds like the problem is something like that in your code.

I don't think I can help. Sorry.

**Comment by douineauromain** [comment]
Ok no problem, just this is my investigation : 
When i test from console it found the "é"
But from my app it found a this strange character : 
![image](https://cloud.githubusercontent.com/assets/8361263/11099398/6427f1d0-88ab-11e5-8ee8-8c35b1ec38a8.png)
Also, diacriticsMap[c] is undefined.

Video : http://recordit.co/UZMJapbg92 

I will try to rename the function as you say...

**Comment by douineauromain** [comment]
Ok so in my case it was to create a file so finally i convert my test to base64 and remove the "=" and then i have a valid file name.

**Comment by sospedra** [comment]
Related. Is not the console. It's about the filenames.
